<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;

class Website extends Model
{
    protected $fillable = ['name', 'type'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        parent::creating(function(Website $website) {
            # Create Web Username Owner from Name
            $website->username = str_slug($website->name);
            $website->password = substr(str_replace("$", "", Hash::make(str_random(8))), 0, 8);
            # Check for Unique
            while (true) {
                $result = shell_exec("grep -c '^{$website->username}:' /etc/passwd");
                if ($result == "0\n") {
                    # Stop While
                    break;
                } else {
                    $website->username .= "-" . substr(Hash::make(str_random(8)), 0, 3);
                }
            }

            # Create Website User in System
            shell_exec("useradd -p `mkpasswd \"{$website->password}\"` -d /home/\"{$website->username}\" -m -g users -s /bin/bash \"{$website->username}\"");

            # Create Directory to Store Deploy source and Version Control
            $website->document_root = "/home/{$website->username}/deploy";
            $website->git_root = "/home/{$website->username}/{$website->username}.git";
            \File::makeDirectory($website->git_root, 770, false, true);
            \File::makeDirectory($website->document_root, 770, false, true);

            # Git Init Bare
            exec("cd {$website->git_root}; git init --bare;");

            # Create Deploy Code
            $deploy_path = "{$website->git_root}/hooks/post-receive";
            \File::put($deploy_path, view('scripts.post-receive', compact('website')));

            # Change Folder Permission
            chownr($website->document_root, $website->username);
            chownr($website->git_root, $website->username);
            chownr($deploy_path, $website->username);

            chgrpr($website->document_root, $website->username);
            chgrpr($website->git_root, $website->username);
            chgrpr($deploy_path, $website->username);

            chmodr($website->document_root, "0770");
            chmodr($website->git_root, "0770");
            chmodr($deploy_path, "0770");
        });

        parent::created(function(Website $website) {
            # Create Sample Virtual Host Config And Store in Storage
            if ($website->type == "Laravel") $website->document_root .= "/public";

            # Store apache config
            $apache_config = view('scripts.sample_apache_config', compact('website'))->render();
            \Storage::drive('local')->put("{$website->id}-{$website->username}.config", $apache_config);
        });
    }

    # Mutators

    # Helpers

}
